# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'
  # vmImage: 'ubuntu-latest'

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: '.NET Restore'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'
    feedsToUse: 'select'
    noCache: true

- task: DotNetCoreCLI@2
  displayName: '.NET Build'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# - task: DotNetCoreCLI@2
#   displayName: '.NET Test'
#   inputs:
#     command: 'test'
#     projects: '**/*[Tt]ests/*.csproj'
#     arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: '.NET Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
    zipAfterPublish: false

- task: FtpUpload@2
  displayName: 'FTP Upload'
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftp://p1860.app.fit.ba'
    username: 'p1860'
    password: 'hRzQuX3!'
    rootDirectory: '$(build.artifactstagingdirectory)/Event_Attender.Web'
    filePatterns: '**'
    remoteDirectory: '/httpdocs/'
    clean: false
    cleanContents: true
    preservePaths: true
    trustSSL: false