// <auto-generated />
using System;
using Eventi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Eventi.Database.Migrations
{
    [DbContext(typeof(EventiContext))]
    [Migration("20201008190006_seedEvent")]
    partial class seedEvent
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Eventi.Domain.Account", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountCategory")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasFilter("[Username] IS NOT NULL");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AccountCategory = 1,
                            Email = "org@eventi.com",
                            PasswordHash = "q0Itx91rdwBxjYgPUhVx3r2fhZ290AgJmepOoO7sEqnRxCbZEhoLQ/ghOGDToA5ZUaa6Khi2kuSNWC23cSvAFQ==",
                            PasswordSalt = "YTd11H/Hm/uR7awLgfA1hw==",
                            Username = "org"
                        });
                });

            modelBuilder.Entity("Eventi.Domain.Administrator", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("Eventi.Domain.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CountryID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CountryID = 1,
                            Name = "Sarajevo"
                        },
                        new
                        {
                            ID = 2,
                            CountryID = 1,
                            Name = "Mostar"
                        },
                        new
                        {
                            ID = 3,
                            CountryID = 1,
                            Name = "Zenica"
                        },
                        new
                        {
                            ID = 4,
                            CountryID = 1,
                            Name = "Tuzla"
                        },
                        new
                        {
                            ID = 5,
                            CountryID = 1,
                            Name = "Banja Luka"
                        },
                        new
                        {
                            ID = 6,
                            CountryID = 1,
                            Name = "Bihać"
                        },
                        new
                        {
                            ID = 7,
                            CountryID = 2,
                            Name = "Zagreb"
                        },
                        new
                        {
                            ID = 8,
                            CountryID = 2,
                            Name = "Split"
                        },
                        new
                        {
                            ID = 9,
                            CountryID = 3,
                            Name = "Beograd"
                        },
                        new
                        {
                            ID = 10,
                            CountryID = 3,
                            Name = "Novi Sad"
                        });
                });

            modelBuilder.Entity("Eventi.Domain.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PersonID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Eventi.Domain.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Croatia"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Serbia"
                        });
                });

            modelBuilder.Entity("Eventi.Domain.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdministratorID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("EventCategory")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AdministratorID");

                    b.HasIndex("OrganizerID");

                    b.HasIndex("VenueID");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(4720),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 959, DateTimeKind.Local).AddTicks(1423),
                            VenueID = 1
                        },
                        new
                        {
                            ID = 2,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6243),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6209),
                            VenueID = 2
                        },
                        new
                        {
                            ID = 3,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6270),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6266),
                            VenueID = 3
                        },
                        new
                        {
                            ID = 4,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6277),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6274),
                            VenueID = 4
                        },
                        new
                        {
                            ID = 5,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6285),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6282),
                            VenueID = 5
                        },
                        new
                        {
                            ID = 6,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6295),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6291),
                            VenueID = 6
                        },
                        new
                        {
                            ID = 7,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6302),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6299),
                            VenueID = 7
                        },
                        new
                        {
                            ID = 8,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6310),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6306),
                            VenueID = 8
                        },
                        new
                        {
                            ID = 9,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6317),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6314),
                            VenueID = 9
                        },
                        new
                        {
                            ID = 10,
                            End = new DateTime(2021, 1, 17, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6326),
                            EventCategory = 0,
                            IsApproved = true,
                            IsCanceled = false,
                            Name = "Event 01",
                            OrganizerID = 1,
                            Start = new DateTime(2021, 1, 16, 21, 0, 5, 961, DateTimeKind.Local).AddTicks(6322),
                            VenueID = 10
                        });
                });

            modelBuilder.Entity("Eventi.Domain.EventPerformer", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("PerformerID")
                        .HasColumnType("int");

                    b.HasKey("EventID", "PerformerID");

                    b.HasIndex("PerformerID");

                    b.ToTable("EventPerformers");
                });

            modelBuilder.Entity("Eventi.Domain.EventSponsor", b =>
                {
                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("SponsorID")
                        .HasColumnType("int");

                    b.Property<int>("SponsorCategory")
                        .HasColumnType("int");

                    b.HasKey("EventID", "SponsorID");

                    b.HasIndex("SponsorID");

                    b.ToTable("EventSponsors");
                });

            modelBuilder.Entity("Eventi.Domain.Organizer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountID")
                        .HasColumnType("int");

                    b.Property<int?>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.HasIndex("CityID");

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AccountID = 1
                        });
                });

            modelBuilder.Entity("Eventi.Domain.Performer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerformerCategory")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Performers");
                });

            modelBuilder.Entity("Eventi.Domain.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Eventi.Domain.Purchase", b =>
                {
                    b.Property<int>("TicketID")
                        .HasColumnType("int");

                    b.Property<int>("ClientID")
                        .HasColumnType("int");

                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfTickets")
                        .HasColumnType("int");

                    b.HasKey("TicketID", "ClientID");

                    b.HasIndex("ClientID");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("Eventi.Domain.RefreshToken", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("AccountID");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Eventi.Domain.Seat", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("SectionID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("SectionID");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("Eventi.Domain.Section", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("VenueID");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Eventi.Domain.Sponsor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("Eventi.Domain.Ticket", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<int>("SeatID")
                        .HasColumnType("int");

                    b.Property<int>("TicketCategory")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EventID");

                    b.HasIndex("SeatID");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Eventi.Domain.Venue", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueCategory")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "Address",
                            CityID = 1,
                            Name = "Venue 01",
                            VenueCategory = 1
                        },
                        new
                        {
                            ID = 2,
                            Address = "Address",
                            CityID = 1,
                            Name = "Venue 02",
                            VenueCategory = 1
                        },
                        new
                        {
                            ID = 3,
                            Address = "Address",
                            CityID = 1,
                            Name = "Venue 03",
                            VenueCategory = 1
                        },
                        new
                        {
                            ID = 4,
                            Address = "Address",
                            CityID = 1,
                            Name = "Venue 04",
                            VenueCategory = 1
                        },
                        new
                        {
                            ID = 5,
                            Address = "Address",
                            CityID = 1,
                            Name = "Venue 05",
                            VenueCategory = 0
                        },
                        new
                        {
                            ID = 6,
                            Address = "Address",
                            CityID = 1,
                            Name = "Venue 06",
                            VenueCategory = 0
                        },
                        new
                        {
                            ID = 7,
                            Address = "Address",
                            CityID = 2,
                            Name = "Venue 07",
                            VenueCategory = 0
                        },
                        new
                        {
                            ID = 8,
                            Address = "Address",
                            CityID = 2,
                            Name = "Venue 08",
                            VenueCategory = 2
                        },
                        new
                        {
                            ID = 9,
                            Address = "Address",
                            CityID = 3,
                            Name = "Venue 09",
                            VenueCategory = 2
                        },
                        new
                        {
                            ID = 10,
                            Address = "Address",
                            CityID = 3,
                            Name = "Venue 10",
                            VenueCategory = 2
                        });
                });

            modelBuilder.Entity("Eventi.Domain.Administrator", b =>
                {
                    b.HasOne("Eventi.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.City", b =>
                {
                    b.HasOne("Eventi.Domain.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.Client", b =>
                {
                    b.HasOne("Eventi.Domain.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.Event", b =>
                {
                    b.HasOne("Eventi.Domain.Administrator", "Administrator")
                        .WithMany()
                        .HasForeignKey("AdministratorID");

                    b.HasOne("Eventi.Domain.Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventi.Domain.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.EventPerformer", b =>
                {
                    b.HasOne("Eventi.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventi.Domain.Performer", "Performer")
                        .WithMany()
                        .HasForeignKey("PerformerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.EventSponsor", b =>
                {
                    b.HasOne("Eventi.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventi.Domain.Sponsor", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.Organizer", b =>
                {
                    b.HasOne("Eventi.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID");

                    b.HasOne("Eventi.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID");
                });

            modelBuilder.Entity("Eventi.Domain.Person", b =>
                {
                    b.HasOne("Eventi.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.Purchase", b =>
                {
                    b.HasOne("Eventi.Domain.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventi.Domain.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.RefreshToken", b =>
                {
                    b.HasOne("Eventi.Domain.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.Seat", b =>
                {
                    b.HasOne("Eventi.Domain.Section", "Section")
                        .WithMany()
                        .HasForeignKey("SectionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.Section", b =>
                {
                    b.HasOne("Eventi.Domain.Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.Ticket", b =>
                {
                    b.HasOne("Eventi.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eventi.Domain.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Eventi.Domain.Venue", b =>
                {
                    b.HasOne("Eventi.Domain.City", "City")
                        .WithMany()
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
